name: Test

on:
  push:
    branches-ignore:
      - main
  workflow_call:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync

      - name: Run linting (ruff)
        run: uv run ruff check

      - name: Run type checking (pyright)
        run: uv run pyright

      - name: Run tests
        run: uv run pytest
